id: P1186A374
initial_creation_type: input
source_metadata:
  title: Hayagrīva Series
  language: bo
  description: 'Texts related to Hayagrīva (rta mgrin), a wrathful manifestation of
    Avalokiteśvara who symbolizes enlightened speech and is usually depicted with
    a horse''s head protruding from his crown:'
  volume:
    b271c3a06fbf455d8f452868c122ef6c:
      title: Fulfilment Offering for Nyangrel Nyima Özer's Treasure Practice of Black
        Hayagrīva with an Iron Sword
      parent: Black Hayagrīva
    02c0b65bd4f5468cbe65d84766f8c820:
      title: Prayer to the Lineage of the Supreme Hayagrīva Emanation from the Aural
        Transmission
      parent: Lineage Prayers
    14637eb21f7f41b1a552d80fee246f19:
      title: Daily Practice of Hayagrīva
      parent: Sādhanas
    d7466a6ede3c417d8505d57a4d6e58b1:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Sādhanas
created_at: '2022-03-01T03:56:44.293064'
last_modified_at: '2022-03-01T03:56:44.293067'
